### ISSUE TITLE
Add Report and Policy samples

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-m3aawg#14]
*Ticket created by request in https://github.com/metanorma/mn-templates-m3aawg/pull/1#issuecomment-730341848*

**Comment by ronaldtse** [comment]
Public policy sample: https://www.m3aawg.org/sites/default/files/m3aawg_final_epdp_comment_clean.pdf

Report sample:
https://www.m3aawg.org/sites/default/files/document/m3aawg_bot_metrics_report1_2012-2013.pdf

**Comment by ronaldtse** [comment]
@manuel489 can you help here? Thanks!

**Comment by manuelfuenmayor** [comment]
Task is pushed and merged. Closing.
